name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '16.x'
          registry-url: https://registry.npmjs.org
          scope: '@pinto'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: build
        run: yarn build
